title: Digital Mentoring for Mathematics
author: Malte Neugebauer
description: Resources for implementing mentoring approaches for mathematical learning in learning management systems.
remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0
plugins:
- jekyll-remote-theme